import {organizeFigures} from '../src/figure-organization.mjs';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {mkdtemp, mkdir, writeFile, readFile, rm, symlink, open, stat, readdir, realpath} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import path from 'node:path';
import os from 'node:os';
import {fileURLToPath} from 'node:url';
import {addDataset, listDatasets, previewDataset, removeDataset, uploadDataset} from '../server/datasets.mjs';
import {researchView, humanTitle, chatMarkdown, metricValue, progressValue} from '../src/research-model.mjs';
import {metricData, metricTables, metricLabel} from '../src/metric-tables.mjs';
import {researchInstructions} from '../server/research-context.mjs';
import {projectEvidenceContext, attachedFigureContext} from '../server/project-evidence.mjs';
import {graphicDirectories, resolveLatexGraphic} from '../server/latex-graphics.mjs';
import './figure-organization-smoke.mjs';
import {executeResearchTool} from '../server/assistant-api.mjs';

const repo = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const temporary = await mkdtemp(path.join(os.tmpdir(), 'science-workbench-research-'));
const root = path.join(temporary, 'study');
await mkdir(root);
const keep = process.argv.includes('--serve');
let server;
try {
  const plannedFigures = organizeFigures([], [{id: 'pilot-01', name: 'Small pilot', experiment: 'Baseline comparison', status: 'running', artifacts: []}], 'experiment:baseline comparison');
  assert.equal(plannedFigures.options[0].label, 'Baseline comparison');
  assert.equal(plannedFigures.options[0].runs[0].label, 'Small pilot');
  assert.equal(plannedFigures.visible.length, 0, 'planned names must not fabricate results');
  const metrics = {linear: {accuracy: .82, auc: .85, brier: .14}, logistic: "{'accuracy': 0.84, 'auc': 0.87, 'brier': 0.13}", n_test: 100};
  const tables = metricTables(metrics);
  assert.deepEqual(tables[0].columns, ['Series', 'accuracy', 'auc', 'brier']);
  assert.deepEqual(tables[0].rows[1], ['logistic', .84, .87, .13]);
  assert.deepEqual(tables[1].rows, [['n_test', 100]]);
  assert.equal(typeof metrics.logistic, 'string', 'display parsing must not mutate research records');
  assert.deepEqual(metricData('{"auc":0.9}'), {auc: .9});
  assert.deepEqual(metricData("{'score': -1.2e-3, 'valid': True, 'other': None,}"), {score: -.0012, valid: true, other: null});
  const hostileMetric = "{'score': __import__('os').system('echo unsafe')}";
  assert.equal(metricData(hostileMetric), hostileMetric, 'never evaluate legacy dictionary strings');
  assert.equal(metricData("{'score': not_a_number}"), "{'score': not_a_number}");
  assert.deepEqual(metricTables({a: {score: 0}, b: {score: 1, extra: 2}})[0].rows[0], ['a', 0, undefined]);
  assert.equal(metricLabel('roc_auc'), 'ROC AUC');
  assert.equal(progressValue(19.166666666666664), '19.2');
  assert.equal(progressValue(100.0000000001), '100');
  assert.equal(metricValue(0.123456789), '0.1235');
  assert.deepEqual(metricTables({confusion: [[10, 2], [3, 8]]})[0].rows, [['1', 10, 2], ['2', 3, 8]]);
  assert.deepEqual(metricTables({folds: [{fold: 1, score: .7}, {fold: 2, score: .8}]})[0].columns, ['Row', 'fold', 'score']);
  assert.deepEqual(metricTables({}), []);
  assert.match(researchInstructions([]), /plotted values and numeric labels must agree/);
  assert.match(researchInstructions([]), /method object in run.json/);
  assert.deepEqual(await listDatasets(root), []);
  const briefRun = {id: 'ready', status: 'complete', completedAt: '2026-01-01T10:00:00Z', metrics: {accuracy: .8}};
  const freshBrief = {summary: 'Measured result', updatedAt: '2026-01-01T05:00:00-05:00'};
  assert.equal(researchView({runs: [briefRun], research: freshBrief}).stale, false, 'compare instants, not timestamp strings');
  assert.equal(researchView({runs: [briefRun], research: {...freshBrief, updatedAt: '2026-01-01T09:59:59Z'}}).stale, true);
  assert.equal(researchView({runs: [{...briefRun, status: 'running'}], research: {...freshBrief, updatedAt: '2025-01-01'}}).stale, false);
  assert.equal(researchView({runs: [briefRun], research: {...freshBrief, updatedAt: 'invalid'}}).stale, false);
  assert.equal(researchView({runs: [briefRun]}).automatic, true);
  assert.match(researchView({runs: [briefRun]}).summary, /Latest completed experiment/);
  assert.equal(researchView({runs: []}).summary, '');
  assert.throws(() => attachedFigureContext({artifacts: []}, '../other/figure.png'), /no longer/);
  const [a, b] = await Promise.all(['first', 'second'].map(name => addDataset(root, {name: name + '.csv', data: Buffer.from('group,value\na,3\nb,5\n').toString('base64')})));
  assert.equal((await listDatasets(root)).length, 2, 'concurrent imports preserve both entries');
  assert.match((await previewDataset(root, a.id)).text, /group,value/);
  const outside = path.join(temporary, 'original.csv');
  await writeFile(outside, 'x,y\n1,2\n');
  const copied = await addDataset(root, {sourcePath: outside});
  await writeFile(path.join(root, copied.path), 'changed workspace copy');
  assert.equal(await readFile(outside, 'utf8'), 'x,y\n1,2\n');
  assert.equal(JSON.stringify(copied).includes(outside), false, 'catalog contains no original machine path');
  const large = await addDataset(root, {name: 'large.csv', data: Buffer.from('x\n'.repeat(40000)).toString('base64')});
  assert.equal((await previewDataset(root, large.id)).text.length, 65536);
  assert.equal((await previewDataset(root, large.id)).truncated, true);
  const maximumUpload = await addDataset(root, {name: 'maximum.csv', data: Buffer.alloc(10 * 1024 * 1024, 65).toString('base64')});
  assert.equal(maximumUpload.bytes, 10 * 1024 * 1024, 'the advertised upload limit must not overflow the regexp stack');
  await removeDataset(root, maximumUpload.id);
  assert.match(await executeResearchTool('read_dataset', {id: a.id}, {cwd: root, mode: 'ask', signal: new AbortController().signal}), /group,value/);
  await removeDataset(root, b.id);
  assert.equal(await readFile(path.join(root, b.path), 'utf8'), 'group,value\na,3\nb,5\n', 'unlink is recoverable and never deletes data');
  assert.equal((await addDataset(root, {name: 'script.sh', data: 'YQ=='})).format, 'sh', 'imports store arbitrary files without executing them');
  await assert.rejects(addDataset(root, {name: 'bad.csv', data: 'invalid!'}), /base64/);
  await assert.rejects(addDataset(root, {sourcePath: '.env'}));
  await assert.rejects(previewDataset(root, 'missing'), /not found/);
  const beforeInterrupted = (await readdir(path.join(root, 'datasets'))).sort();
  const interrupted = Readable.from((async function* () {
    yield Buffer.from('--fixture-boundary\r\nContent-Disposition: form-data; name="files"; filename="partial.pdf"\r\nContent-Type: application/pdf\r\n\r\npartial data');
    await new Promise(resolve => setTimeout(resolve, 20));
    throw new Error('Simulated disconnect');
  })());
  interrupted.headers = {'content-type': 'multipart/form-data; boundary=fixture-boundary'};
  await assert.rejects(uploadDataset(root, interrupted, 'partial.pdf'), /interrupted/);
  assert.deepEqual((await readdir(path.join(root, 'datasets'))).sort(), beforeInterrupted, 'interrupted uploads leave no partial workspace copy');
  const dataFolder = path.join(temporary, 'mixed-data');
  await mkdir(path.join(dataFolder, 'nested'), {recursive: true});
  await writeFile(path.join(dataFolder, 'nested', 'paper.pdf'), '%PDF fixture');
  await writeFile(path.join(dataFolder, 'interview.mp3'), Buffer.from([0, 255, 1]));
  await writeFile(path.join(dataFolder, '.env'), 'PRIVATE_FIXTURE');
  const importedFolder = await addDataset(root, {sourcePath: dataFolder});
  assert.equal(importedFolder.kind, 'directory');
  assert.equal(importedFolder.fileCount, 2);
  assert.equal(importedFolder.skipped, 1);
  assert.equal(await readFile(path.join(root, importedFolder.path, 'nested/paper.pdf'), 'utf8'), '%PDF fixture');
  assert.equal((await previewDataset(root, importedFolder.id)).text, null);
  await assert.rejects(addDataset(root, {sourcePath: root}), /project itself/);
  await assert.rejects(addDataset(root, {sourcePath: path.join(root, 'datasets')}), /already inside/);
  const bigPath = path.join(temporary, 'large-recording.mp3');
  const bigHandle = await open(bigPath, 'w');
  await bigHandle.truncate(257 * 1024 * 1024);
  await bigHandle.close();
  const bigImport = await addDataset(root, {sourcePath: bigPath});
  assert.equal((await stat(path.join(root, bigImport.path))).size, 257 * 1024 * 1024, 'native picker imports exceed the former 256 MB cap');
  await rm(path.join(root, bigImport.path));
  await removeDataset(root, bigImport.id);

  if (process.platform !== 'win32') {
    const other = path.join(temporary, 'symlink-project'); await mkdir(other);
    await symlink(temporary, path.join(other, 'datasets'));
    await assert.rejects(addDataset(other, {name: 'data.csv', data: 'YQ=='}), /inaccessible|Symlinks/);
  }
  assert.equal(humanTitle('toy-linear-20260904-013216_linear_fit.svg'), 'Toy linear linear fit');
  assert.equal(chatMarkdown('[long name](/workspace/Study A/artifacts/figures/my plot.svg)', '/workspace/Study A'), '[Long name](artifacts/figures/my%20plot.svg)');
  assert.equal(chatMarkdown('`[x](/workspace/Study A/artifacts/figures/my plot.svg)`', '/workspace/Study A'), '`[x](/workspace/Study A/artifacts/figures/my plot.svg)`');
  assert.equal(researchView({runs: [{id: 'r1'}], research: {findings: [{text: 'Unlinked finding', runIds: ['absent']}]}}).findings[0].missingEvidence, true);
  assert.equal(researchView({research: {findings: [{text: 'Malformed evidence list', runIds: 'not-an-array'}]}}).findings[0].missingEvidence, true);
  for (const folder of ['runs/baseline-01', 'artifacts/figures/nested', 'research', 'exports', 'assistant']) await mkdir(path.join(root, folder), {recursive: true});
  await writeFile(path.join(root, 'workbench.project.json'), JSON.stringify({name: 'Interface regression study', researchQuestion: 'How does a baseline behave on a controlled dataset?', phase: 'analysis'}));
  await writeFile(path.join(root, 'runs/baseline-01/run.json'), JSON.stringify({id: 'baseline-01', name: 'Baseline · held-out evaluation', experiment: 'Understanding the baseline', status: 'complete', progress: 100, startedAt: '2026-01-01T00:00:00Z', completedAt: '2026-01-01T00:01:00Z', logs: ['Loaded data.', 'Evaluated baseline.'], parameters: {seed: 7}, method: {objective: 'Compare two controlled fixture models.', split: '**Held-out** interface fixture, 100 samples.', steps: ['Load the controlled fixture.', 'Evaluate both model outputs.', 'Record scores and export diagnostics.']}, metrics: {accuracy: .82, sample_count: 100, ...metrics}, artifacts: ['artifacts/figures/nested/baseline.svg']}));
  const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="900" height="500"><rect width="900" height="500" fill="white"/><text x="80" y="50" font-size="24">Baseline diagnostic (fixture)</text><path d="M80 90V420H840" fill="none" stroke="#203040" stroke-width="2"/><path d="M100 370L220 310L340 300L460 190L580 160L700 120L820 100" fill="none" stroke="#4c7c98" stroke-width="5"/><text x="430" y="475" font-size="20">Evaluation step</text></svg>';
  await writeFile(path.join(root, 'artifacts/figures/nested/baseline.svg'), svg);
  await writeFile(path.join(root, 'artifacts/figures/comparison.svg'), svg.replace('Baseline diagnostic', 'Comparison diagnostic'));
  await writeFile(path.join(root, 'artifacts/figures/metadata.json'), JSON.stringify({figures: [{path: 'artifacts/figures/nested/baseline.svg', title: 'Baseline diagnostic', caption: 'A controlled fixture showing the baseline across evaluation steps.', interpretation: 'Interface test data, not a scientific conclusion.', topic: 'Model checks', runId: 'baseline-01', runIds: ['baseline-01']}]}));
  await writeFile(path.join(root, 'research/summary.json'), JSON.stringify({updatedAt: '2026-01-01T00:02:00Z', summary: '**Controlled comparison.** This fixture checks that experiment evidence populates the workbench.', findings: [{text: '**Logistic has the higher fixture score.** Both models use the same 100-sample evaluation. This is interface test data, not a scientific conclusion.', runIds: ['baseline-01']}], limitations: ['Synthetic interface test only.'], nextSteps: ['Inspect the readable figure and run metadata.']}));
  await writeFile(path.join(root, 'exports/main.render.pdf'), 'compiler intermediate');
  await writeFile(path.join(root, 'assistant/experiment.py'), '# Research code is not a chat job');
  const env = {...process.env, WORKBENCH_PROJECT_ROOT: root, WORKBENCH_STATE_PATH: path.join(temporary, 'state.json'), WORKBENCH_PROVIDER_SETTINGS_PATH: path.join(temporary, 'providers.json'), WORKBENCH_PORT: '8896', WORKBENCH_CODEX_PATH: path.join(repo, 'scripts/fixtures/assistant-rpc.mjs'), ...Object.fromEntries(['CLAUDE', 'GEMINI', 'OPENCODE', 'PI'].map(id => [`WORKBENCH_${id}_PATH`, path.join(temporary, 'missing')]))};
  for (const name of ['OPENAI_API_KEY', 'ANTHROPIC_API_KEY', 'GEMINI_API_KEY', 'GOOGLE_API_KEY', 'WORKBENCH_COMPATIBLE_API_KEY']) env[name] = '';
  server = spawn(process.execPath, ['server/index.mjs'], {cwd: repo, env, stdio: ['ignore', 'pipe', 'pipe']});
  let logs = ''; server.stdout.on('data', data => logs += data); server.stderr.on('data', data => logs += data);
  const base = 'http://127.0.0.1:8896';
  for (let i = 0; i < 60; i++) { try { if ((await fetch(base + '/api/health')).ok) break; } catch { /* retry startup */ } await new Promise(resolve => setTimeout(resolve, 100)); }
  assert.equal(server.exitCode, null, logs);
  const request = async (route, body) => { const response = await fetch(base + route, body ? {method: 'POST', headers: {'content-type': 'application/json'}, body: JSON.stringify(body)} : {}); assert.equal(response.ok, true, await response.clone().text()); return response.json(); };
  const project = await request('/api/project');
  assert.equal(project.root, root, 'use only the isolated test service');
  assert.equal(project.runs[0].metrics.accuracy, .82);
  assert.equal(project.runs[0].cancellable, false);
  assert.equal(project.runs[0].method.steps.length, 3);
  assert.equal(metricTables(project.runs[0].metrics)[0].rows[1][1], .84);
  assert.equal(project.artifacts.find(item => item.path.endsWith('/baseline.svg')).title, 'Baseline diagnostic');
  assert.equal(project.artifacts.find(item => item.path.endsWith('/baseline.svg')).topic, 'Model checks');
  assert.deepEqual(project.artifacts.find(item => item.path.endsWith('/baseline.svg')).runIds, ['baseline-01']);
  assert.ok(!project.artifacts.some(item => item.path.includes('.render.')));
  assert.ok(project.files.includes('assistant/experiment.py'));
  assert.equal(researchView(project).findings[0].missingEvidence, false);
  const saveDocument = body => fetch(base + '/api/writeups/source', {method: 'PUT', headers: {'content-type': 'application/json'}, body: JSON.stringify(body)});
  assert.equal((await saveDocument({format: 'markdown', source: '# Retained draft', expectedSource: ''})).status, 200);
  assert.equal((await request('/api/writeups/source?format=markdown')).source, '# Retained draft');
  assert.equal((await saveDocument({format: 'markdown', source: '# Stale replacement', expectedSource: ''})).status, 409);
  assert.equal((await request('/api/writeups/source?format=markdown')).source, '# Retained draft', 'source conflict must preserve existing text');
  const rawSource = await fetch(base + '/writeups/main.md');
  assert.equal(rawSource.status, 200);
  assert.match(rawSource.headers.get('content-type'), /text\/plain/);
  assert.equal(await rawSource.text(), '# Retained draft');
  assert.equal((await fetch(base + '/writeups/main.tex')).status, 404);
  assert.equal((await saveDocument({format: 'markdown', source: 'wrong project', projectRoot: '/not-active'})).status, 409);
  const dirs = graphicDirectories('\\graphicspath{{../artifacts/figures/}{../artifacts/figures/nested/}}');
  assert.deepEqual(dirs, ['../artifacts/figures/', '../artifacts/figures/nested/']);
  const resolvedFigure = await realpath(path.join(root, 'artifacts/figures/nested/baseline.svg'));
  assert.equal(await resolveLatexGraphic(path.join(root, 'writeups/main.tex'), 'baseline.svg', root, dirs), resolvedFigure);
  assert.equal(await resolveLatexGraphic(path.join(root, 'writeups/main.tex'), 'baseline', root, dirs), resolvedFigure);
  await assert.rejects(resolveLatexGraphic(path.join(root, 'writeups/main.tex'), 'original.csv', root, ['../../']), /not found/);
  const imported = await request('/api/datasets', {name: 'http-data.csv', data: 'eCx5CjEsMgo='});
  assert.equal((await request(`/api/datasets/${imported.dataset.id}/preview`)).text, 'x,y\n1,2\n');
  await request(`/api/datasets/${imported.dataset.id}/remove`, {});
  const multipart = async (name, entries, folder = false, extra = '') => {
    const body = new FormData();
    for (const [filename, data] of entries) body.append('files', new Blob([data]), encodeURIComponent(filename));
    return fetch(`${base}/api/datasets/upload?name=${encodeURIComponent(name)}${folder ? '&folder=1' : ''}${extra}`, {method: 'POST', body});
  };
  const uploaded = await multipart('large.pdf', [['large.pdf', Buffer.alloc(12 * 1024 * 1024, 65)]]);
  assert.equal(uploaded.status, 201, await uploaded.clone().text());
  assert.equal((await uploaded.json()).dataset.bytes, 12 * 1024 * 1024, 'browser picker streams above the former 10 MB cap');
  const folderUpload = await multipart('browser-folder', [['nested/résumé.pdf', '%PDF'], ['sound.mp3', 'audio'], ['.env', 'PRIVATE_FIXTURE']], true);
  assert.equal(folderUpload.status, 201, await folderUpload.clone().text());
  const folderDataset = (await folderUpload.json()).dataset;
  assert.equal(folderDataset.fileCount, 2);
  assert.equal(folderDataset.skipped, 1);
  assert.equal(await readFile(path.join(root, folderDataset.path, 'nested/résumé.pdf'), 'utf8'), '%PDF');
  const beforeRejected = (await readdir(path.join(root, 'datasets'))).sort();
  for (const entries of [[['../escape.pdf', 'bad']], [['same.pdf', 'first'], ['same.pdf', 'duplicate']]]) {
    const rejected = await multipart('unsafe-folder', entries, true);
    assert.equal(rejected.status, 400, await rejected.text());
    assert.deepEqual((await readdir(path.join(root, 'datasets'))).sort(), beforeRejected, 'failed folder uploads remove partial files');
  }
  const staleUpload = await multipart('wrong-project.pdf', [['paper.pdf', 'fixture']], false, '&projectRoot=wrong');
  assert.equal(staleUpload.status, 409);
  const secretUpload = await multipart('.env', [['.env', 'PRIVATE_FIXTURE']]);
  assert.equal(secretUpload.status, 400);
  const hostile = await fetch(base + '/api/datasets', {method: 'POST', headers: {origin: 'https://untrusted.example', 'content-type': 'application/json'}, body: JSON.stringify({name: 'data.csv', data: 'YQ=='})});
  assert.equal(hostile.status, 403);
  const turn = async (conversationId, message, extra = {}) => {
    const job = await request('/api/assistant', {conversationId, message, permissionMode: 'ask', selection: {adapterId: 'codex', modelId: 'test-model', effort: 'low'}, ...extra});
    for (let i = 0; i < 80; i++) {
      const current = await request(`/api/assistant/${job.id}`);
      if (current.status !== 'running') return current;
      await new Promise(resolve => setTimeout(resolve, 50));
    }
    throw new Error('Fixture assistant did not finish');
  };
  const firstChat = (await request('/api/assistant/conversations', {role: 'experiment'})).conversation;
  const firstTurn = await turn(firstChat.id, 'FIXTURE_STATE first conversation');
  assert.equal(firstTurn.status, 'complete');
  const secondChat = (await request('/api/assistant/conversations', {role: 'experiment'})).conversation;
  const secondTurn = await turn(secondChat.id, 'FIXTURE_STATE second conversation');
  assert.notEqual(firstTurn.sessionId, secondTurn.sessionId, 'new conversations have independent native context');
  const resumed = await turn(firstChat.id, 'FIXTURE_STATE resume first');
  assert.equal(resumed.sessionId, firstTurn.sessionId);
  assert.equal(JSON.parse(resumed.output).turns, 2);
  const failed = await turn(firstChat.id, 'Train logistic regression with loss and confusion matrix. FIXTURE_FAIL');
  assert.equal(failed.status, 'failed');
  const continuation = await turn(firstChat.id, 'FIXTURE_PROMPT proceed');
  const context = JSON.parse(continuation.output).prompt;
  assert.match(context, /User: Train logistic regression with loss and confusion matrix/);
  assert.match(context, /Assistant \(failed\)/);
  assert.doesNotMatch(context, /second conversation/);
  assert.match(context, /Current assistant selection.*"model":"test-model"/);
  assert.match(context, /Questions, greetings, model identity.*without project edits/);
  const isolatedHistory = await request(`/api/assistant?conversationId=${secondChat.id}`);
  assert.deepEqual(isolatedHistory.jobs.map(job => job.id), [secondTurn.id]);
  const wrongRole = await fetch(base + '/api/assistant', {method: 'POST', headers: {'content-type': 'application/json'}, body: JSON.stringify({conversationId: firstChat.id, role: 'writing', message: 'No cross-role context', selection: {adapterId: 'codex', modelId: 'test-model', effort: 'low'}})});
  assert.equal(wrongRole.status, 404);
  const emptyChat = (await request('/api/assistant/conversations', {role: 'writing'})).conversation;
  assert.ok((await request('/api/assistant')).conversations.some(item => item.id === emptyChat.id), 'empty chats are durable');
  const writingTurn = await turn(emptyChat.id, 'FIXTURE_PROMPT Write a summary of the work so far.', {role: 'writing', artifactPath: 'artifacts/figures/nested/baseline.svg'});
  const writingPrompt = JSON.parse(writingTurn.output).prompt;
  assert.match(writingPrompt, /persist both name .* and experiment .* before|Before computation starts, persist both name/);
  assert.match(writingPrompt, /status queued before computation/);
  assert.match(writingPrompt, /Shared project evidence/);
  assert.match(writingPrompt, /Selected editor format for this request: markdown/);
  assert.match(writingPrompt, /Markdown source to writeups\/main.md/);
  assert.match(writingPrompt, /research\/summary.json/);
  assert.doesNotMatch(writingPrompt, /"accuracy":0.82/);
  assert.match(writingPrompt, /do not read experiment history automatically/);
  assert.match(writingPrompt, /A fresh conversation does not mean no research/);
  assert.match(writingPrompt, /Attached project figure reference/);
  assert.equal(writingTurn.artifactPath, 'artifacts/figures/nested/baseline.svg');
  const figureEdit = await turn(firstChat.id, 'FIXTURE_PROMPT Make the legend smaller on this figure.', {artifactPath: 'artifacts/figures/nested/baseline.svg'});
  const figurePrompt = JSON.parse(figureEdit.output).prompt;
  for (const prompt of [figurePrompt, writingPrompt]) {
    assert.match(prompt, /Revise existing figures in place by default/);
    assert.match(prompt, /re-render only that figure from saved data\/results/);
    assert.match(prompt, /replace the existing export at the same project-relative path/);
    assert.match(prompt, /Update its metadata entry by path, preserving runId\/runIds/);
    assert.match(prompt, /explicitly requested alternatives/);
    assert.match(prompt, /Pass these revision constraints and the exact target path to any delegated worker/);
  }
  assert.equal(figureEdit.artifactPath, 'artifacts/figures/nested/baseline.svg');
  assert.doesNotMatch(projectEvidenceContext({...project, models: {apiKey: 'secret-fixture'}, infrastructure: {token: 'secret-fixture'}}), /secret-fixture/);
  // Older histories have no conversation ID. They remain available beyond the old 30-job cap.
  for (let i = 0; i < 32; i++) {
    const id = `assistant-legacy-fixture-${String(i).padStart(2, '0')}`;
    await mkdir(path.join(root, 'assistant', id));
    await writeFile(path.join(root, 'assistant', id, 'job.json'), JSON.stringify({id, role: 'writing', message: `Legacy request ${i}`, output: 'Legacy response', status: 'complete', startedAt: `2025-01-01T00:00:${String(i).padStart(2, '0')}Z`}));
  }
  const legacy = await request('/api/assistant?conversationId=legacy-writing');
  assert.equal(legacy.jobs.length, 32);
  assert.equal(legacy.jobs[0].message, 'Legacy request 0');
  assert.equal((await request('/api/assistant?allConversations=1')).jobs.length, 39);
  const pending = await request('/api/assistant', {conversationId: secondChat.id, message: 'FIXTURE_HANG', permissionMode: 'ask', selection: {adapterId: 'codex', modelId: 'test-model', effort: 'low'}});
  await request('/api/datasets', {name: 'while-chat-runs.csv', data: 'eCx5CjEsMgo='});
  await request(`/api/assistant/${pending.id}/cancel`, {});
  console.log('Conversation smoke passed: independent chats, resume, retained failed requests, prompt scope, role isolation, durable empty chats, complete legacy history, and datasets during a task.');
  console.log('Research smoke passed: dataset upload/import/preview/unlink, bounded reads, original preservation, secret/symlink/origin rejection, live run metrics, nested figures, metadata, summaries, and legacy links.');
  if (keep) { console.log(`Isolated UI fixture ready: ${base} (Ctrl+C to stop)`); await new Promise(resolve => process.once('SIGINT', resolve)); }
} finally {
  if (server && server.exitCode === null) { server.kill('SIGTERM'); await new Promise(resolve => server.once('close', resolve)); }
  await rm(temporary, {recursive: true, force: true});
}
