import React, {useContext, useEffect, useRef, useState} from 'react';
import {FeedbackContext} from './WorkspaceFeedback.jsx';
import './figure-actions.css';
export default function FigureActions({figure, projectRoot, close, onRemoved}) {
  const context = useContext(FeedbackContext), dialog = useRef(null), keep = useRef(null);
  const [review, setReview] = useState(null), [removed, setRemoved] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const request = (action, body) => context.request(`/api/figures/${action}`, {method: 'POST', headers: {'x-axiovela-project': projectRoot}, body: JSON.stringify(body)});
  useEffect(() => { const before = document.activeElement; dialog.current.showModal(); return () => before?.isConnected && before.focus(); }, []);
  useEffect(() => { if (review && !removed) keep.current?.focus(); }, [review]);
  const act = async fn => { setBusy(true); setError(''); try { await fn(); } catch(e) { setError(e.message); } finally { setBusy(false); } };
  useEffect(() => { let canceled = false; setBusy(true); request('preview-removal', {path: figure.path}).then(value => { if (!canceled) setReview(value); }).catch(e => { if (!canceled) setError(e.message); }).finally(() => { if (!canceled) setBusy(false); }); return () => { canceled = true; }; }, [figure.path, projectRoot]);
  return <dialog className="figureActionDialog" ref={dialog} onCancel={e => { e.preventDefault(); if (!busy) close(); }} aria-labelledby="figure-action-title"><header><h3 id="figure-action-title">{removed ? 'Figure moved to trash' : 'Move this figure to trash?'}</h3><button aria-label="Close figure actions" disabled={busy} onClick={close}>×</button></header><p className="figureActionPath">{figure.path}</p>
    {removed ? <><p>Your next message will automatically include a request to clean up this figure’s generating code and current project references. Later messages will also remind the assistant not to recreate it.</p><p>Cleanup follows the chat’s access level and preserves shared code and chat history. Restore the figure to cancel this reminder.</p><small>Backup: {removed.backup}</small><button disabled={busy} onClick={() => act(async () => { await request('restore', {id: removed.id}); onRemoved?.(); close(); })}>Undo removal</button><button onClick={close}>Done</button></> : <><p>Move the image to recoverable storage and ask the assistant to clean up its generating code and current references with your next message.</p><p>The assistant will keep it excluded on later turns, preserve shared work and respect the chat’s access level. You can undo this or restore it from Removed figures.</p>{review ? <details><summary>{review.references.length} matching reference files{review.truncated ? ' (limited scan)' : ''}</summary>{review.references.map(name => <div key={name} className="figureActionPath">{name}</div>)}<small>Literal filename matches only. The assistant will inspect dependencies before editing.</small></details> : <p role="status">{error ? 'Could not review this figure. Close and try again.' : 'Checking figure and references…'}</p>}<div className="figureActionButtons"><button ref={keep} autoFocus disabled={busy} onClick={close}>Keep figure</button><button className="figureDanger" disabled={busy || !review} onClick={() => act(async () => { const result = await request('remove', {path: figure.path, revision: review.revision}); setRemoved(result); onRemoved?.(figure.path); })}>{busy ? 'Working…' : 'Trash figure'}</button></div></>}
    {error && <p role="alert">{error}</p>}
  </dialog>;
}
export function RemovedFigures({projectRoot, onRestore}) {
  const context = useContext(FeedbackContext), [items, setItems] = useState(null), [error, setError] = useState('');
  const request = (url, options={}) => context.request(url, {...options, headers:{'x-axiovela-project':projectRoot}});
  return <details className="removedFigures" onToggle={e => { if(e.currentTarget.open) request('/api/figures/removed').then(r=>setItems(r.figures)).catch(e=>setError(e.message)); }}><summary>Removed figures</summary>{items?.length === 0 && <p>No removed figures.</p>}{items?.map(item=><div key={item.id}><span>{item.path}</span><button onClick={async()=>{try { await request('/api/figures/restore',{method:'POST',body:JSON.stringify({id:item.id})}); setItems(list=>list.filter(x=>x.id!==item.id)); onRestore?.(); }catch(e){setError(e.message);}}}>Restore</button></div>)}{error&&<p role="alert">{error}</p>}</details>;
}
