import React, {useContext, useEffect, useRef, useState} from 'react';
import {FeedbackContext} from './WorkspaceFeedback.jsx';
import './figure-actions.css';
export default function FigureActions({figure, projectRoot, close, onRemoved}) {
  const context = useContext(FeedbackContext), dialog = useRef(null);
  const [review, setReview] = useState(null), [removed, setRemoved] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const request = (action, body) => context.request(`/api/figures/${action}`, {method: 'POST', headers: {'x-axiovela-project': projectRoot}, body: JSON.stringify(body)});
  useEffect(() => { const before = document.activeElement; dialog.current.showModal(); return () => before?.isConnected && before.focus(); }, []);
  const act = async fn => { setBusy(true); setError(''); try { await fn(); } catch(e) { setError(e.message); } finally { setBusy(false); } };
  const draft = () => { context.draftFollowup?.(`Review cleanup for figure ${figure.path}. Find the generating code and references in write-ups, metadata, and discussion. Propose precise changes and explain shared dependencies before editing. Preserve unrelated results and conversation history. The figure ${removed ? 'has been moved to recoverable storage' : 'has not been removed'}.`); close(); };
  return <dialog className="figureActionDialog" ref={dialog} onCancel={e => { e.preventDefault(); if (!busy) close(); }} aria-labelledby="figure-action-title"><header><h3 id="figure-action-title">{removed ? 'Figure removed' : review ? 'Remove this figure?' : 'Figure actions'}</h3><button aria-label="Close figure actions" disabled={busy} onClick={close}>×</button></header><p className="figureActionPath">{figure.path}</p>
    {removed ? <><p>The file is in project recovery storage. Code, write-ups, metadata and discussion remain unchanged.</p><small>Backup: {removed.backup}</small><button disabled={busy} onClick={() => act(async () => { await request('restore', {id: removed.id}); onRemoved?.(); close(); })}>Undo removal</button><button onClick={draft}>Draft cleanup review in chat</button></> : review ? <><p>Move this file to recoverable storage. Existing references may show a missing figure until restored or revised.</p><p>Code and discussion are preserved. Shared scripts can produce other figures.</p><details><summary>{review.references.length} matching reference files{review.truncated ? ' (limited scan)' : ''}</summary>{review.references.map(name => <div key={name} className="figureActionPath">{name}</div>)}<small>Literal filename matches only. Generated paths, renamed figures and external references may be missed.</small></details><div className="figureActionButtons"><button disabled={busy} onClick={close}>Keep figure</button><button className="figureDanger" disabled={busy} onClick={() => act(async () => { const result = await request('remove', {path: figure.path, revision: review.revision}); setRemoved(result); onRemoved?.(figure.path); })}>{busy ? 'Working…' : 'Remove figure'}</button></div></> : <div role="menu" aria-label="Figure actions" onKeyDown={e => { const buttons = [...e.currentTarget.querySelectorAll('[role=menuitem]')], at = buttons.indexOf(document.activeElement); const next = e.key === 'ArrowDown' ? (at + 1) % buttons.length : e.key === 'ArrowUp' ? (at + buttons.length - 1) % buttons.length : e.key === 'Home' ? 0 : e.key === 'End' ? buttons.length - 1 : -1; if (next >= 0) { e.preventDefault(); buttons[next].focus(); } }}><button role="menuitem" autoFocus disabled={busy} onClick={() => act(async () => setReview(await request('preview-removal', {path: figure.path})))}>Remove figure…</button><button role="menuitem" onClick={draft}>Review code &amp; references in chat</button></div>}
    {error && <p role="alert">{error}</p>}
  </dialog>;
}
export function RemovedFigures({projectRoot, onRestore}) {
  const context = useContext(FeedbackContext), [items, setItems] = useState(null), [error, setError] = useState('');
  const request = (url, options={}) => context.request(url, {...options, headers:{'x-axiovela-project':projectRoot}});
  return <details className="removedFigures" onToggle={e => { if(e.currentTarget.open) request('/api/figures/removed').then(r=>setItems(r.figures)).catch(e=>setError(e.message)); }}><summary>Removed figures</summary>{items?.length === 0 && <p>No removed figures.</p>}{items?.map(item=><div key={item.id}><span>{item.path}</span><button onClick={async()=>{try { await request('/api/figures/restore',{method:'POST',body:JSON.stringify({id:item.id})}); setItems(list=>list.filter(x=>x.id!==item.id)); onRestore?.(); }catch(e){setError(e.message);}}}>Restore</button></div>)}{error&&<p role="alert">{error}</p>}</details>;
}
