import React from 'react';
import RichText from './ResearchText.jsx';
import {metricLabel, metricTables} from './metric-tables.mjs';
import FigureGallery from './FigureGallery.jsx';
import {figureTitle, humanTitle, metricValue, researchView, runTitle} from './research-model.mjs';

function Empty({children}) { return <div className="emptyResearch"><p>{children}</p></div>; }
function Metrics({metrics, compact = false}) {
  const tables = metricTables(metrics);
  if (!tables.length) return compact ? null : <Empty>No metrics recorded yet.</Empty>;
  const shown = compact ? tables.filter(table => table.comparison).slice(0, 1) : tables;
  if (!shown.length && compact) shown.push(...tables.slice(0, 1).map(table => ({...table, rows: table.rows.slice(0, 4)})));
  return <div className={'researchMetrics' + (compact ? ' compactMetrics' : '')}>{shown.map((table, index) => <div className="metricTableScroll" key={index} role="region" aria-label={table.title} tabIndex={0}><table className="metricTable"><caption>{table.title}</caption><thead><tr>{table.columns.map((column, i) => <th key={i} scope="col"><RichText inline text={metricLabel(column)}/></th>)}</tr></thead><tbody>{table.rows.map((row, i) => <tr key={i}>{row.map((value, j) => j === 0 ? <th key={j} scope="row" title={String(value)}><RichText inline text={metricLabel(value)}/></th> : <td key={j} title={value === undefined ? 'Not recorded' : JSON.stringify(value)}>{typeof value === 'string' ? <RichText inline text={value}/> : value === undefined || value === null ? '—' : metricValue(value)}</td>)}</tr>)}</tbody></table></div>)}{!compact && <details><summary>Exact recorded values</summary><pre>{JSON.stringify(metrics, null, 2)}</pre></details>}</div>;
}
function ExperimentDetails({run}) {
  if (!run) return <Empty>Select a recorded experiment to inspect its procedure.</Empty>;
  const method = run.method && typeof run.method === 'object' && !Array.isArray(run.method) ? run.method : {};
  return <div className="researchBrief"><h3><RichText inline text={runTitle(run)}/></h3>{run.summary && <RichText text={run.summary}/>}<dl><dt>Experiment</dt><dd>{run.experiment || 'Not recorded'}</dd><dt>Run ID</dt><dd>{run.id}</dd><dt>Status</dt><dd>{run.status}</dd><dt>Started</dt><dd>{run.startedAt || 'Not recorded'}</dd><dt>Completed</dt><dd>{run.completedAt || 'Not completed'}</dd><dt>Tracker</dt><dd>{run.source?.adapter || 'native'}</dd></dl><h4>Procedure</h4>{Object.keys(method).length ? Object.entries(method).map(([key, value]) => <section key={key}><h4><RichText inline text={metricLabel(key)}/></h4>{Array.isArray(value) ? <ol>{value.map((step, i) => <li key={i}><RichText text={typeof step === 'string' ? step : JSON.stringify(step)}/></li>)}</ol> : <RichText text={typeof value === 'string' ? value : JSON.stringify(value)}/>}</section>) : <p>A procedure outline was not recorded for this run. Parameters and execution logs below are the available record.</p>}{run.command && <><h4>Command</h4><pre>{typeof run.command === 'string' ? run.command : JSON.stringify(run.command)}</pre></>}<h4>Parameters</h4><Metrics metrics={run.parameters}/>{run.error && <p role="alert" className="renderError">{run.error}</p>}<details><summary>Environment</summary><pre>{JSON.stringify(run.environment || {}, null, 2)}</pre></details><h4>Recorded artifact paths</h4>{run.artifacts?.length ? <ul>{run.artifacts.map((item, i) => <li key={i}><code>{typeof item === 'string' ? item : item.path}</code></li>)}</ul> : <p>No artifact paths recorded for this run.</p>}</div>;
}
function Logs({run}) { return run?.logs?.length ? <ol className="researchLogs">{run.logs.map((line, index) => <li key={index}>{typeof line === 'string' ? line : JSON.stringify(line)}</li>)}</ol> : <Empty>Execution messages appear here as the experiment writes its run log.</Empty>; }

function trialDate(value) {
  if (!value) return '—';
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleString(undefined, {dateStyle: 'medium', timeStyle: 'short'});
}
function TrialControls({run, cancelRun, runError}) {
  return <>{run.error && <p role="alert" className="renderError">{run.error}</p>}{run.cancellable ? <button className="lightBtn" onClick={() => cancelRun(run.id)}>Cancel trial</button> : run.status === 'running' && <p className="paneHint">Stop this task in its assistant chat or external tracker.</p>}{runError && <p role="alert" className="renderError">{runError}</p>}</>;
}

export function ResearchLeft({Pane, tab, project, selectedRun, selectRun, infrastructure}) {
  const view = researchView(project);
  const question = project?.manifest?.researchQuestion;
  if (tab === 'Trials') return <Pane title="Trial ledger"><p className="paneHint trialLedgerHint">{view.runs.length} recorded · updates from saved experiment records</p>{view.runs.length ? <div className="trialLedger">{view.runs.map(run => <button key={run.id} aria-pressed={run.id === selectedRun?.id} className={run.id === selectedRun?.id ? 'selected' : ''} onClick={() => selectRun(run.id)}><span className="trialHeading"><b><RichText inline text={runTitle(run)}/></b><span className="trialStatus">{run.status}</span></span>{run.experiment && <small className="trialExperiment"><RichText inline text={run.experiment}/></small>}<span className="trialMeta"><code>{run.id}</code><time dateTime={run.startedAt || undefined}>{trialDate(run.startedAt)}</time></span></button>)}</div> : <Empty>No trials recorded yet. Ask the assistant to run an experiment and record its results.</Empty>}</Pane>;
  if (tab === 'Methods') return <><Pane title="Experiment outline"><div className="researchHypothesis"><h3>Hypothesis / research question</h3><RichText text={project?.manifest?.hypothesis || question || 'Define the study question in chat.'}/></div><div className="evidenceRunPicker"><label htmlFor="evidence-run">Experiment</label><select id="evidence-run" value={selectedRun?.id || view.runs[0]?.id || ''} onChange={event => selectRun(event.target.value)}>{!view.runs.length && <option value="">No experiments yet</option>}{view.runs.map(run => <option key={run.id} value={run.id}>{runTitle(run)} · {run.status}</option>)}</select></div><ExperimentDetails run={selectedRun || view.runs[0]}/></Pane><Pane title="Project setup"><div className="projectSetupContent">{infrastructure}<h3>Project code</h3>{project?.files?.length ? <div className="fileInventory">{project.files.map(file => <code key={file}>{file}</code>)}</div> : <Empty>No source files recorded yet.</Empty>}{project?.datasets?.length > 0 && <><h3>Datasets</h3><ul>{project.datasets.map(item => <li key={item.id}>{item.name}</li>)}</ul></>}</div></Pane></>;
  const linkedRuns = view.stale ? view.runs.filter(run => run.status === 'complete') : view.findings.length ? view.runs.filter(run => view.findings.some(finding => finding.runs.includes(run.id))) : view.runs.slice(0, 1);
  const overview = <div className="researchBrief executiveBrief"><div className="researchCounts"><span><b>{view.completed}</b> completed</span><span><b>{view.active}</b> active</span><span><b>{view.artifacts.length}</b> artifacts</span></div>{question && <h3 className="researchQuestion"><RichText inline text={question}/></h3>}{view.summary ? <><small>{view.automatic ? 'RESEARCH BRIEF · RECORDED EXPERIMENTS' : 'RESEARCH BRIEF · ASSISTANT/AUTHOR SYNTHESIS'}</small><RichText text={view.summary}/>{view.stale && <p className="warningText">This brief predates a completed experiment; newer measurements are shown below.</p>}</> : <Empty>{view.runs.length ? (view.active ? 'Experiment in progress. Recorded outcomes will appear here automatically.' : 'No completed experiments yet. Run status and logs are available on Trials.') : 'Start a study in chat. Findings will appear here after an experiment.'}</Empty>}{view.findings.length > 0 && <><h4>Findings</h4>{view.findings.map((finding, i) => <section className="researchFinding" key={i}><RichText text={finding.text}/><small>{finding.missingEvidence ? 'Evidence references incomplete. ' : 'Linked evidence: '}{finding.runs.map(id => runTitle(view.runs.find(run => run.id === id))).join(' · ')}</small></section>)}</>}{linkedRuns.length > 0 && <><h4>Key recorded results</h4>{linkedRuns.map(run => <section key={run.id} className="briefComparison"><strong><RichText inline text={runTitle(run)}/></strong><Metrics metrics={run.metrics} compact/>{metricTables(run.metrics).length > 0 ? <small>Rounded display · full metrics and procedure on Methods</small> : <p className="pendingMetrics">{run.status === 'running' || run.status === 'queued' ? 'Measurements pending.' : 'No metrics recorded.'}</p>}</section>)}</>}{view.limitations.length > 0 && <><h4>Limitations</h4><ul>{view.limitations.map((text, i) => <li key={i}><RichText text={text}/></li>)}</ul></>}{view.completed > 0 && !view.limitations.length && <p className="researchCaveat">Point estimates alone do not establish uncertainty or generalization. Review sample sizes, baselines, and diagnostics in Methods.</p>}</div>;
  return <Pane title="Study brief"><div className="studyBriefContent">{overview}<div className="researchBrief"><h4>Recommended next moves</h4><ol>{(view.nextSteps.length ? view.nextSteps : !project?.root ? ['Open or create a project using the top bar.'] : !view.runs.length ? ['State a research question and link the relevant dataset.', 'Ask the assistant to define a baseline and run a small reproducible pilot.'] : [view.failed ? 'Inspect failed run logs and resolve the reported errors.' : 'Review the recorded findings and figure interpretations.', 'Check robustness across seeds or held-out data and quantify uncertainty.', 'Draft the supported findings with citations and limitations.']).map((text, i) => <li key={i}><RichText text={text}/></li>)}</ol></div></div></Pane>;
}

export function ResearchMiddle({Pane, tab, project, selectedRun, apiBase, cancelRun, runError}) {
  const latest = selectedRun || project?.runs?.[0];
  if (tab === 'Trials') return <Pane title="Trial record">{latest ? <div className="researchBrief trialRecord"><h3><RichText inline text={runTitle(latest)}/></h3><dl><dt>Experiment</dt><dd>{latest.experiment || 'Not recorded'}</dd><dt>Status</dt><dd>{latest.status}</dd><dt>Started</dt><dd>{trialDate(latest.startedAt)}</dd><dt>Finished</dt><dd>{trialDate(latest.completedAt)}</dd><dt>Tracker</dt><dd>{latest.source?.adapter || 'native'}</dd></dl>{latest.summary && <RichText text={latest.summary}/>}<TrialControls run={latest} cancelRun={cancelRun} runError={runError}/><h4>Recorded metrics</h4><Metrics metrics={latest.metrics}/><details><summary>Execution log · {latest.logs?.length || 0} entries</summary><Logs run={latest}/></details><details><summary>Parameters and environment</summary><pre>{JSON.stringify({parameters: latest.parameters || {}, environment: latest.environment || {}}, null, 2)}</pre></details><details><summary>Artifacts · {latest.artifacts?.length || 0}</summary>{latest.artifacts?.length ? <ul>{latest.artifacts.map((item, i) => <li key={i}><code>{typeof item === 'string' ? item : item.path}</code></li>)}</ul> : <p>No artifact paths recorded.</p>}</details></div> : <Empty>Select a trial to inspect its recorded results.</Empty>}</Pane>;
  if (tab === 'Methods') return <><Pane title="Experiment record">{latest && <p className="metricSource">{runTitle(latest)} · {latest.status}</p>}<Metrics metrics={latest?.metrics}/></Pane><Pane title="Execution log"><Logs run={latest}/></Pane></>;
  return <Pane title="Results and artifacts"><FigureGallery projectRoot={project?.root} key={project?.root} artifacts={project?.artifacts} runs={project?.runs} apiBase={apiBase}/></Pane>;
}
